api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats: []
    defaults:
        format: json
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_client_enabled: true
        extra_properties:
              symfony:
                trailing_slash: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
