security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/token(/|$)
            stateless: true
            json_login:
                check_path: /api/token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~  # <== Auth via JWT token

        main:
            lazy: true
            provider: users_in_database

    access_control:
        # Autorise tout le monde à obtenir un token
        - { path: ^/api/token, roles: PUBLIC_ACCESS }
        # Autorise tous les endpoints API avec JWT valide
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
