vich_uploader:
    db_driver: orm

    mappings:
        plant_photos:
            uri_prefix: /uploads/plant_photos
            upload_destination: '%kernel.project_dir%/public/uploads/plant_photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
