parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Normalizers (si tu continues à utiliser la sérialisation personnalisée)
    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer: ~
    App\Serializer\SnakeCaseNormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object'
        tags:
            - { name: 'serializer.normalizer', priority: 10 }

    # Événement auth JWT (si tu utilises toujours LexikJWTAuthenticationBundle)
    App\Security\AuthenticationSuccessHandler:
        tags:
            - { name: 'kernel.event_listener', event: lexik_jwt_authentication.on_authentication_success, method: __invoke }

    # Service de conseils (encore utilisé dans les contrôleurs)
    App\Service\PlantAdviceService: ~
    App\Service\Paginator:
        arguments:
            $router: '@router'
